M48
; DRILL file KiCad 10.0.0 date 2026-03-31T12:14:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-31T12:14:31+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X117.14Y-85.91
X117.14Y-91.69
T2
X121.6Y-122.87
X136.6Y-36.8
X145.1Y-36.8
M30
